services:
  api-postgres:
    image: postgres:16-alpine
    container_name: api-postgres-dev
    environment:
      POSTGRES_USER: identity_access
      POSTGRES_PASSWORD: identity_access_dev_password
      POSTGRES_DB: identity_access
    ports:
      - '5433:5432'
    volumes:
      - api-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U identity_access']
      interval: 5s
      timeout: 5s
      retries: 5

  api-redis:
    image: redis:7-alpine
    container_name: api-redis-dev
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  api-minio:
    image: minio/minio:latest
    container_name: api-minio-dev
    environment:
      MINIO_ROOT_USER: hospital_dev
      MINIO_ROOT_PASSWORD: hospital_dev_password
    command: server /data --console-address ":9001"
    ports:
      - '9002:9000'
      - '9003:9001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  api-postgres-data:
